### ISSUE TITLE
A problem about :find the scaled l2 norm for each filter this layer

### ISSUE THREAD

**Issue by Chinese-xingyi** [wanglouis49/pytorch-weights_pruning#2]
in file "/pruning/methods" ,the code:  
value_this_layer = np.square(p_np).sum(axis=1).sum(axis=1)\
                .sum(axis=1)/(p_np.shape[1]*p_np.shape[2]*p_np.shape[3])

Should not the axis are 0,2,3?and shape[0],shape[2],shape[3],so the code is 
value_this_layer = np.square(p_np).sum(axis=0).sum(axis=2)\
                .sum(axis=3)/(p_np.shape[0]*p_np.shape[2]*p_np.shape[3])?

Thank you!

**Comment by wanglouis49** [comment]
No, the implementation is correct. First, in the denominator, note that in PyTorch `axis=0` corresponds to the output channel - we wanna to normalize per the output channel so we need to consider all the weights form input channels (`p_np.shape[1]`) times weights in each kernel (`p_np.shape[2] * p_np.shape[3]`). Then in the numerator, it should be written in a clearer form as `.sum(axis=(1, 2, 3))`.

Thank you for you comments. This part is for sure not written in the most readable way. In fact, I have re-written all the code here purely in PyTorch and made it clearer. I'll release it in the near future.
