### ISSUE TITLE
change the models

### ISSUE THREAD

**Issue by ssxlconch** [wanglouis49/pytorch-weights_pruning#3]
sorry for bothering,
I want to prune VGG16 or LeNet, but I don't know how to generate the pretrain.pkl
Could you please tell me the method to generate pretrain.pkl ?
 maybe, would you mind to send me your source code for generating convnet_pretrained.pkl files?
my e-mail address is 2741592109@qq.com
Thank you for help!

**Comment by wanglouis49** [comment]
Thanks for your question. Generating `pretrain.pkl` is straightforward. Just comment [these lines](https://github.com/wanglouis49/pytorch-weights_pruning/blob/master/weight_pruning.py#L47-L51) and change parameters and filename accordingly.
